---
title: "Loading data"
output: html_notebook
---

### Installing packages

```{r Packages, message=FALSE, warning=FALSE}
rm(list = ls())
# ######################################################################################
# Set working directory
# wdir <- "U:/datacodeR/"
wdir <- "Y:/agrajg/Airbnb_data/AirbnbDataCodeMay2017/datacodeR"
# ######################################################################################
# # Packages
# ######################################################################################
# update.packages()
# install.packages("tidyr", lib =  paste(wdir,"library", sep = "/"))
# install.packages("dplyr", lib =  paste(wdir,"library", sep = "/"))
# install.packages("ggplot2", lib =  paste(wdir,"library", sep = "/"))
# install.packages("magrittr", lib =  paste(wdir,"library", sep = "/"))
# ######################################################################################
library("magrittr", lib.loc=paste(wdir,"library", sep = "/"))
library("dplyr", lib.loc=paste(wdir,"library", sep = "/"))
library("tidyr", lib.loc=paste(wdir,"library", sep = "/"))
library("ggplot2", lib.loc=paste(wdir,"library", sep = "/"))
# ######################################################################################

```

### Loading data 
The data is being cleaned in stata and then being converted into R data using "1DataLoadingSaving_v11.R" file

```{r Load data}
# ######################################################################################
# ######################################################################################
      # # Load Sample Data
      # setwd(wdir)
      # load("airdna_market_data_sample50.RData")
      # load("mcox_listing_data_sample50.RData")
      # load("airdna_listing_data_sample50.RData")
# ######################################################################################
# ######################################################################################
      # Load Actual Data
      setwd(wdir)
      load("airdna_market_data.RData")
      load("mcox_listing_data.RData")
      load("airdna_listing_data.RData")
# # ######################################################################################
# ######################################################################################
```



```{r SPARK}
# ######################################################################################
# install.packages("sparklyr")
library(sparklyr)
spark_install(version = "2.0.2", hadoop_version = "2.7", reset = TRUE,  logging = "INFO", verbose = interactive())
sc <- spark_connect(master = "local", version = "2.0.2", hadoop_version = "2.7")
# ######################################################################################
# Copying data on to spark
setwd(wdir)
market.data <- copy_to(sc, market.data, "market_data" , overwrite = TRUE)
airdna.listing.data <- copy_to(sc, airdna.listing.data, "airdna_listing_data" , overwrite = TRUE)
mcox.listing.data <- copy_to(sc, mcox.listing.data, "mcox_listing_data" , overwrite = TRUE)
# ######################################################################################
```




```{r}
# str(market.data)
# str(airdna.listing.data)
# str(mcox.listing.data)
```


```{r}
# hosts.data <- airdna.listing.data %>%
#   select(propertyid, hostid)
# market.data <- market.data %>%
#   left_join(.,hosts.data)
# market.data %>%
#   summarise(num.property =  n_distinct(propertyid), time.horizon = n_distinct(date),num.host = n_distinct(hostid))
```



